In [2]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr2=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,6,7,7,8]])
arr2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 6, 7, 7, 8]])

In [6]:
arr1.shape

(5,)

In [23]:
arr1.ndim

1

In [9]:
arr2.shape

(2, 8)

In [45]:
arr9=np.array([[[1,2],[2,3]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr10=np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
arr10


array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [15]:
arr10.shape

(2, 2, 2)

In [21]:
arr2


array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 6, 7, 7, 8]])

In [22]:
arr2.ndim

2

In [25]:
arr11 = np.array([[[[1,2],[3,4]], [[5,6],[7,8]]], [[[9,10],[11,12]], [[13,14],[15,16]]]])
arr11

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [26]:
arr11.shape

(2, 2, 2, 2)

In [27]:
arr12 = np.array([[[[1,2],[3,4]]], [[[9,10],[11,12]]]])
arr12


array([[[[ 1,  2],
         [ 3,  4]]],


       [[[ 9, 10],
         [11, 12]]]])

In [32]:
print(arr12.shape)
print(arr12.ndim)


(2, 1, 2, 2)
4


here, shape (2,1,2,2) attributes to:                                  
                             🔹 First number: 2
At the outermost level, there are 2 big elements.
Each of these "big elements" is still a nested structure, not a simple number.
(Think of it like two main folders.)

🔹 Second number: 1
Inside each "big element," there is 1 group.
(Each folder has exactly one subfolder.)

🔹 Third number: 2
Inside that 1 group, there are 2 rows.
(The subfolder has 2 files stacked vertically.)

🔹 Fourth number: 2
Each row has 2 columns (2 numbers).
(Each file has 2 numbers side-by-side.)



In [28]:
arr13 = np.array([[[[1,2]]], [[[9,10]]]])
arr13

array([[[[ 1,  2]]],


       [[[ 9, 10]]]])

In [33]:
arr14 = np.array([[[[1,2,3],[3,4,5]]], [[[9,10,11],[11,12,5]]]])
arr14

array([[[[ 1,  2,  3],
         [ 3,  4,  5]]],


       [[[ 9, 10, 11],
         [11, 12,  5]]]])

In [34]:
print(arr14.shape)
print(arr14.ndim)

(2, 1, 2, 3)
4


In [35]:
arr14.size

12

number of items are size.

In [36]:
arr14.itemsize

8

The amount of memory (in bytes) that one element of the array takes. Why 8 bytes here?                                                                         
Because by default, NumPy stores integers as int64 (64 bits = 8 bytes). tem size does NOT depend on the shape of the array.                                                                                                        
✅ It only depends on the data type (dtype) of the elements inside.

So, for your array with shape (2, 1, 2, 3):

Shape tells how many elements you have.

Itemsize tells how big each single element is.





In [37]:
arr14.dtype


dtype('int64')

In [38]:
arr8=np.linspace(10,25,10)
arr8

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        , 21.66666667, 23.33333333, 25.        ])

In [39]:
arr8.dtype

dtype('float64')

In [41]:
arr10.dtype

dtype('int64')

In [46]:
arr9

array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [7, 8]]])

In [47]:
arr9.dtype

dtype('int64')

In [48]:
arr9.astype('float')

array([[[1., 2.],
        [2., 3.]],

       [[5., 6.],
        [7., 8.]]])

In [49]:
arr8.astype('int')

array([10, 11, 13, 15, 16, 18, 20, 21, 23, 25])

In [51]:
arr15=np.array(['a','b','c'])
arr15.dtype

dtype('<U1')



1.   < = little-endian (you don't have to care much here)
2.   U = Unicode string
3.   1 = each item can store 1 character (because your strings were only 'a', 'b', 'c' — 1 character each)








