<a href="https://colab.research.google.com/github/sammywenthikingwithshroomtrolls/Data-Analysis-Numpy/blob/main/Some_important_numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.random()

0.5359723029397991

In [4]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [5]:
np.random.uniform(3,10)


8.042271454095108

In [6]:
np.random.uniform(1,100,10)

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [7]:
np.random.uniform(1,100,10).reshape(2,5)

array([[21.24077272, 87.9336262 ,  3.71137173, 67.37628351, 42.31317543],
       [56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ]])

In [8]:
np.random.randint(1,10)

7

In [9]:
np.random.randint(1,10,15).reshape(3,5)

array([[2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9]])

In [11]:
a=np.random.randint(1,10,6)
a

array([2, 5, 1, 4, 3, 1])

In [12]:
np.max(a)

np.int64(5)

In [13]:
np.min(a)

np.int64(1)

In [15]:
np.sin(a)

array([ 0.90929743, -0.95892427,  0.84147098, -0.7568025 ,  0.14112001,
        0.84147098])

In [16]:
np.argmax(a)

np.int64(1)

In [17]:
a[np.argmax(a)]

np.int64(5)

In [18]:
a[np.argmin(a)]

np.int64(1)

In [20]:
a=np.random.randint(1,110,6)
a

array([ 26, 105,  23,  10,  68, 104])

In [22]:
a[a%2==1]=-1
a

array([ 26,  -1,  -1,  10,  68, 104])

replaced all the odd number with -1

In [23]:
a=np.random.randint(1,50,6)
a

array([24, 37, 28, 38, 20, 39])

In [24]:
np.where(a%2==1,-1,a)

array([24, -1, 28, 38, 20, -1])

In [25]:
out=np.where(a%2==1,-1,a)
out

array([24, -1, 28, 38, 20, -1])

In [26]:
a=np.random.randint(1,50,10)
a

In [27]:
a=np.sort(a)
a

array([ 8,  9, 11, 16, 24, 24, 26, 33, 35, 48])

In [28]:
np.percentile(a,25)

np.float64(12.25)

In [29]:
np.percentile(a,50)

np.float64(24.0)

In [30]:
np.percentile(a,99.8)

np.float64(47.76599999999999)